[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
rustui = {path = "../rustui"}
properties = {path = "../properties"}
tokio = { version = "1.40.0", features = ["full"] }

[[bin]]
name = "example"
path = "main.rs"
