[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
helium = {path = "../helium"}
tokio = { version = "1.40.0", features = ["full"] }
env_logger = "0.11.5"
log = "0.4.22"

[[bin]]
name = "example"
path = "main.rs"
