[workspace]
resolver = "2"

members = [
	"helium", 
	"examples", 
	"helium_macros", 
	"helium_core", 
	"crystal",
]

[workspace.dependencies]
thiserror = "2.0.9"
tokio = { version = "1.40.0", features = ["full"] }

