[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
helium = { path = "../helium", features = ["icon-sets"]}
env_logger = "0.11.5"
log = "0.4.22"

[[example]]
name = "counter"
path = "counter.rs"

[[example]]
name = "spotify"
path = "spotify/spotify.rs"

[[example]]
name = "sign_in"
path = "pages/sign_in.rs"

[dependencies]
dotenv = "0.15.0"
tokio.workspace = true